### ISSUE TITLE
wdconvect extern.F90 compilation fails with Intel v19.0.0.117

### ISSUE THREAD

**Issue by bcfriesen** [AMReX-Astro/MAESTROeX#40] opened 2019-02-22 18:49 UTC
With the 19.02 releases of AMReX, Microphysics, and MAESTROeX, compilation of `extern.F90` in `MAESTROeX/Exec/SCIENCE/wdconvect` using the Intel v19.0.0.117 compilers fails as follows:

```
extern.F90(153): error #6576: If a namelist-group-name has the PUBLIC attribute, no item in the namelist-group-object-list may have the PRIVATE attribute.   [VELPERT_AMPLITUDE]
  namelist /probin/ velpert_amplitude
--------------------^
extern.F90(154): error #6576: If a namelist-group-name has the PUBLIC attribute, no item in the namelist-group-object-list may have the PRIVATE attribute.   [VELPERT_RADIUS]
  namelist /probin/ velpert_radius
--------------------^
extern.F90(155): error #6576: If a namelist-group-name has the PUBLIC attribute, no item in the namelist-group-object-list may have the PRIVATE attribute.   [VELPERT_SCALE]
  namelist /probin/ velpert_scale
--------------------^
extern.F90(156): error #6576: If a namelist-group-name has the PUBLIC attribute, no item in the namelist-group-object-list may have the PRIVATE attribute.   [VELPERT_STEEP]
  namelist /probin/ velpert_steep
--------------------^
extern.F90(157): error #6576: If a namelist-group-name has the PUBLIC attribute, no item in the namelist-group-object-list may have the PRIVATE attribute.   [TAG_DENSITY_1]
  namelist /probin/ tag_density_1
--------------------^
extern.F90(158): error #6576: If a namelist-group-name has the PUBLIC attribute, no item in the namelist-group-object-list may have the PRIVATE attribute.   [TAG_DENSITY_2]
  namelist /probin/ tag_density_2
--------------------^
extern.F90(159): error #6576: If a namelist-group-name has the PUBLIC attribute, no item in the namelist-group-object-list may have the PRIVATE attribute.   [TAG_DENSITY_3]
  namelist /probin/ tag_density_3
--------------------^
extern.F90(160): error #6576: If a namelist-group-name has the PUBLIC attribute, no item in the namelist-group-object-list may have the PRIVATE attribute.   [PARTICLE_TEMP_CUTOFF]
  namelist /probin/ particle_temp_cutoff
--------------------^
extern.F90(161): error #6576: If a namelist-group-name has the PUBLIC attribute, no item in the namelist-group-object-list may have the PRIVATE attribute.   [PARTICLE_TPERT_THRESHOLD]
  namelist /probin/ particle_tpert_threshold
--------------------^
extern.F90(162): error #6576: If a namelist-group-name has the PUBLIC attribute, no item in the namelist-group-object-list may have the PRIVATE attribute.   [USE_EOS_COULOMB]
  namelist /probin/ use_eos_coulomb
--------------------^
extern.F90(163): error #6576: If a namelist-group-name has the PUBLIC attribute, no item in the namelist-group-object-list may have the PRIVATE attribute.   [EOS_INPUT_IS_CONSTANT]
  namelist /probin/ eos_input_is_constant
--------------------^
extern.F90(164): error #6576: If a namelist-group-name has the PUBLIC attribute, no item in the namelist-group-object-list may have the PRIVATE attribute.   [EOS_TTOL]
  namelist /probin/ eos_ttol
--------------------^
extern.F90(165): error #6576: If a namelist-group-name has the PUBLIC attribute, no item in the namelist-group-object-list may have the PRIVATE attribute.   [EOS_DTOL]
  namelist /probin/ eos_dtol
--------------------^
extern.F90(166): error #6576: If a namelist-group-name has the PUBLIC attribute, no item in the namelist-group-object-list may have the PRIVATE attribute.   [SMALL_X]
  namelist /probin/ small_x
--------------------^
extern.F90(167): error #6576: If a namelist-group-name has the PUBLIC attribute, no item in the namelist-group-object-list may have the PRIVATE attribute.   [USE_TABLES]
  namelist /probin/ use_tables
--------------------^
extern.F90(168): error #6576: If a namelist-group-name has the PUBLIC attribute, no item in the namelist-group-object-list may have the PRIVATE attribute.   [USE_C12AG_DEBOER17]
  namelist /probin/ use_c12ag_deboer17
--------------------^
extern.F90(169): error #6576: If a namelist-group-name has the PUBLIC attribute, no item in the namelist-group-object-list may have the PRIVATE attribute.   [ODE_MAX_STEPS]
  namelist /probin/ ode_max_steps
--------------------^
extern.F90(170): error #6576: If a namelist-group-name has the PUBLIC attribute, no item in the namelist-group-object-list may have the PRIVATE attribute.   [SCALING_METHOD]
  namelist /probin/ scaling_method
--------------------^
extern.F90(171): error #6576: If a namelist-group-name has the PUBLIC attribute, no item in the namelist-group-object-list may have the PRIVATE attribute.   [USE_TIMESTEP_ESTIMATOR]
  namelist /probin/ use_timestep_estimator
--------------------^
extern.F90(172): error #6576: If a namelist-group-name has the PUBLIC attribute, no item in the namelist-group-object-list may have the PRIVATE attribute.   [ODE_SCALE_FLOOR]
  namelist /probin/ ode_scale_floor
--------------------^
extern.F90(173): error #6576: If a namelist-group-name has the PUBLIC attribute, no item in the namelist-group-object-list may have the PRIVATE attribute.   [ODE_METHOD]
  namelist /probin/ ode_method
--------------------^
extern.F90(174): error #6576: If a namelist-group-name has the PUBLIC attribute, no item in the namelist-group-object-list may have the PRIVATE attribute.   [SAFETY_FACTOR]
  namelist /probin/ safety_factor
--------------------^
extern.F90(175): error #6576: If a namelist-group-name has the PUBLIC attribute, no item in the namelist-group-object-list may have the PRIVATE attribute.   [DO_CONSTANT_VOLUME_BURN]
  namelist /probin/ do_constant_volume_burn
--------------------^
extern.F90(176): error #6576: If a namelist-group-name has the PUBLIC attribute, no item in the namelist-group-object-list may have the PRIVATE attribute.   [CALL_EOS_IN_RHS]
  namelist /probin/ call_eos_in_rhs
--------------------^
extern.F90(177): error #6576: If a namelist-group-name has the PUBLIC attribute, no item in the namelist-group-object-list may have the PRIVATE attribute.   [DT_CRIT]
  namelist /probin/ dT_crit
--------------------^
extern.F90(178): error #6576: If a namelist-group-name has the PUBLIC attribute, no item in the namelist-group-object-list may have the PRIVATE attribute.   [BURNING_MODE]
  namelist /probin/ burning_mode
--------------------^
extern.F90(179): error #6576: If a namelist-group-name has the PUBLIC attribute, no item in the namelist-group-object-list may have the PRIVATE attribute.   [BURNING_MODE_FACTOR]
  namelist /probin/ burning_mode_factor
--------------------^
extern.F90(180): error #6576: If a namelist-group-name has the PUBLIC attribute, no item in the namelist-group-object-list may have the PRIVATE attribute.   [INTEGRATE_TEMPERATURE]
  namelist /probin/ integrate_temperature
--------------------^
extern.F90(181): error #6576: If a namelist-group-name has the PUBLIC attribute, no item in the namelist-group-object-list may have the PRIVATE attribute.   [INTEGRATE_ENERGY]
  namelist /probin/ integrate_energy
--------------------^
extern.F90(182): error #6576: If a namelist-group-name has the PUBLIC attribute, no item in the namelist-group-object-list may have the PRIVATE attribute.   [JACOBIAN]
  namelist /probin/ jacobian
--------------------^
/tmp/ifortO5xWJ0.i90(527): catastrophic error: Too many errors, exiting
```

This error is new with Intel v19; it does not occur for any release of the v18 compilers.

**Comment by ajnonaka** [comment] 2019-02-22 19:14
Using the default modules on cori, currently MAESTROeX wdconvect only compiles with gnu.  Cray fails in addition to Intel.

**Comment by bcfriesen** [comment] 2019-02-22 23:42
Actually I can compile it with any of the v18 Intel compilers. However, at run time, both Intel v18 and the Cray compiler (v8.7.7) throw a namelist error:

```bash
friesen@nid02305:~/MAESTROeX/Exec/SCIENCE/wdconvect> srun -n 1 ./Maestro3d.intel.mic-knl.MPI.ex inputs_3d_C.128
MPI initialized with 1 MPI processes
AMReX (19.02-dirty) initialized
Calling Setup()
Calling ReadParameters()
reading extern runtime parameters ...
 ERROR: problem in the namelist
friesen@nid02305:~/MAESTROeX/Exec/SCIENCE/wdconvect>
```

**Comment by zingale** [comment] 2020-01-16 01:42
this is a duplicate of #108

**Closed by zingale** 2020-01-16 01:42 UTC
